// lib/localization/app_localizations_fa.dart
class AppLocalizationsFa {
  static const Map<String, String> strings = {
    'app_name': 'شناساگر گیاه',
    'welcome': 'خوش آمدید',
    'login': 'ورود',
    'register': 'ثبت‌نام',
    'email': 'ایمیل',
    'password': 'رمز عبور',
    'confirm_password': 'تکرار رمز عبور',
    'name': 'نام',
    'take_photo': 'عکس بگیرید',
    'recent_scans': 'اسکن‌های اخیر',
    'plant_name': 'نام گیاه',
    'health_status': 'وضعیت سلامت',
    'disease': 'بیماری',
    'treatment': 'درمان',
    'care_instructions': 'دستورالعمل مراقبت',
    'history': 'تاریخچه',
    'profile': 'پروفایل',
    'settings': 'تنظیمات',
    'language': 'زبان',
    'english': 'انگلیسی',
    'persian': 'فارسی',
    'dark_mode': 'حالت تاریک',
    'back': 'بازگشت',
    'next': 'بعدی',
    'get_started': 'شروع کنید',
  };
}